[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/upload"
  status = 200
